export TERM="xterm-256color"
export ZSH=$HOME/.oh-my-zsh
export EDITOR='vim'
export GOPATH=$HOME/go
export TERM="xterm-256color"
export HOME=$HOME
export PATH="$PATH:$HOME/.rvm/bin:/usr/local/go/bin:$HOME/go/bin:$HOME/bin:$HOME/.local/bin" # Add RVM to PATH for scripting
export BIG="$HOME/lists/seclists/Discovery/Web-Content/big.txt"
export WEB="$HOME/lists/seclists/Discovery/Web-Content/"
export DIRS_LARGE="$HOME/lists/seclists/Discovery/Web-Content/raft-large-directories.txt"
export DIRS_SMALL="$HOME/lists/seclists/Discovery/Web-Content/raft-small-directories.txt"
export FILES_LARGE="$HOME/lists/seclists/Discovery/Web-Content/raft-large-files.txt"
export FILES_SMALL="$HOME/lists/seclists/Discovery/Web-Content/raft-small-files.txt"
# added by pipsi (https://github.com/mitsuhiko/pipsi)

# -------------------------------- aliases ---------------------------------
alias ls=" ls --color -sh"
alias wclone="wget -H -p -k"
alias nmap="grc nmap"
alias netstat="grc netstat"
alias ping="grc ping"
alias tail="grc tail"
alias ps="grc ps"



ZSH_THEME="mrtazz"
plugins=(doctl encode64 vi-mode dircycle github z rails zsh-navigation-tools docker docker-compose vagrant cp ruby nmap common-aliases)

source $ZSH/oh-my-zsh.sh
source ~/.profile

# -------------------------------- FUNCTIONS ---------------------------------

function bin2sc() {
    # convert .bin to shellcode
    hexdump -v -e '"\\""x" 1/1 "%02x" ""' ${1}
}

function ctf-tools() {
    sudo docker run --rm -it zardus/ctf-tools "$@"
}

function ciphey() {
    sudo docker run -it --rm remnux/ciphey "$@"
}

function dockershell() {
    sudo docker run --rm -i -t --entrypoint=/bin/bash "$@"
}

function dockershellsh() {
    sudo docker run --rm -i -t --entrypoint=/bin/sh "$@"
}

function dockershellhere() {
    dirname=${PWD##*/}
    sudo docker run --rm -it --entrypoint=/bin/bash -v `pwd`:/${dirname} -w /${dirname} "$@"
}

function dockershellshhere() {
    sudo docker run --rm -it --entrypoint=/bin/sh -v `pwd`:/${dirname} -w /${dirname} "$@"
}

function dockerwindowshellhere() {
    dirname=${PWD##*/}
    sudo docker -c 2019-box run --rm -it -v "C:${PWD}:C:/source" -w "C:/source" "$@"
}

function impacket() {
    sudo docker run --rm -it rflathers/impacket "$@"
}

function intrigue-ident() {
    sudo docker run -t intrigueio/intrigue-ident -u "$@"
}

function smbservehere() {
    local sharename
    [[ -z $1 ]] && sharename="SHARE" || sharename=$1
    sudo docker run --rm -it -p 445:445 -v "${PWD}:/tmp/serve" rflathers/impacket smbserver.py -smb2support $sharename /tmp/serve
}

function nginxhere() {
    sudo docker run --rm -it -p 80:80 -p 443:443 -v "${PWD}:/srv/data" rflathers/nginxserve
}

function webdavhere() {
    sudo docker run --rm -it -p 80:80 -v "${PWD}:/srv/data/share" rflathers/webdav
}

function metasploit() {
    sudo docker run --rm -it  --network=host metasploitframework/metasploit-framework ./msfconsole "$@"
}

function msfvenomhere() {
    sudo docker run --rm -it -v "${HOME}/.msf4:/home/msf/.msf4" -v "${PWD}:/data" metasploitframework/metasploit-framework ./msfvenom "$@"
}

function postfiledumphere() {
    sudo docker run --rm -it -p80:3000 -v "${PWD}:/data" rflathers/postfiledump
}

function reqdump() {
    sudo docker run --rm -it -p 80:3000 rflathers/reqdump
}

#EOF
